name: Publish Patch Version

on: 
  push:
      branches: ['master']

  workflow_dispatch:
  repository_dispatch:
  
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH
        
      - name: Install dependencies
        run: bun deps
   
      - name: Compile code
        run: bun compile

      - name: Publish
        run: |
          git config --global user.name "James A. Prempeh"
          git config --global user.email agyemanjp@danfortsystems.com
          bun pub:patch
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        

